# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SubsetRaster
                                 A QGIS plugin
 This plugin allows user to create subset of a raster.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-26
        copyright            : (C) 2026 by Murat Çalışkan
        email                : caliskan.murat.20@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SubsetRaster class from file SubsetRaster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .subset_raster import SubsetRaster
    return SubsetRaster(iface)
