# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SubsetRasterDialog
                                 A QGIS plugin
 This plugin allows user to create subset of a raster.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-26
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Murat Çalışkan
        email                : caliskan.murat.20@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'subset_raster_dialog_base.ui'))


class SubsetRasterDialog(QtWidgets.QDialog, QtWidgets.QApplication, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SubsetRasterDialog, self).__init__(parent)
        self.setupUi(self)
